language: python
python:
   - "3.6"

services:
  - docker

install:
  - touch varsettings.env
  - echo "SECRET_KEY=Thisisatestkey" >> varsettings.env
  - echo "DEBUG=True" >> varsettings.env
  - docker-compose up -d
script:
  - docker exec -ti thewallproject_web_1 bash -c "cd thewall;python3 manage.py migrate;python3 manage.py test"
