language: python
python:
   - "3.6"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - touch varsettings.env
  - docker-compose up -d
  - docker ps 
script:
  - docker exec thewallproject_web_1 /bin/sh -c "cd thewall;python3 manage.py test"
