language: python
python:
   - "3.6"

services:
  - docker

install:
  - touch varsettings.env
  - docker-compose up -d
  - docker ps 
script:
  - docker exec -ti thewallproject_web_1 bash -c "cd thewall;python3 manage.py test"
