language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - touch varsettings.env
  - sudo ls
  - docker-compose up -d
script:
  - docker exec thewallproject_web_1 /bin/sh -c "cd thewall;python3 manage.py test"
