language: python
python:
  -"3.5"
  -"3.6"
  -"3.7"

services:
  - docker

before_install:
  - touch varsettings.env
  - sudo ls
  - docker-compose up -d
script:
  - docker exec thewallproject_web_1 /bin/sh -c "cd thewall;python3 manage.py test"
