version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    env_file:
      - varsettings.env
    command: bash -c "python3 thewall/manage.py makemigrations thewallapp && python3 thewall/manage.py migrate && python3 thewall/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db